-- ============================================================
-- Migration 122: Create idp_drafts table
-- ============================================================
-- Stores AI-auto-drafted Individual Development Plans (IDPs)
-- generated by the coaching-nudges cron job when a rep falls
-- below 80% KPI attainment for 3+ consecutive weeks.
--
-- Human-in-the-loop: all drafts start as 'pending_review'.
-- Managers approve or reject before any IDP is shared with reps.
--
-- Consumed by:
--   - Cron: runCoachingNudges() → inserts 'pending_review' rows
--   - API:  GET /api/pilot/adoption-signals → counts reviewed rows
--   - API:  (future) GET /api/coaching/idp-drafts — manager review queue
-- ============================================================

CREATE TABLE IF NOT EXISTS idp_drafts (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Who this IDP is for
  profile_id        UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Manager who owns the coaching relationship (nullable — admin-triggered drafts may lack one)
  manager_id        UUID        REFERENCES profiles(id) ON DELETE SET NULL,

  -- Org scoping — required for RLS
  organization_id   UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

  -- AI-generated IDP content (structured JSON from Haiku)
  -- Schema mirrors server.js prompt response:
  --   { development_goal, focus_areas[], weekly_actions[], success_metric, review_cadence }
  draft_content     JSONB       NOT NULL DEFAULT '{}',

  -- Workflow state
  status            TEXT        NOT NULL DEFAULT 'pending_review'
                                CHECK (status IN ('pending_review', 'approved', 'rejected', 'converted_to_idp')),

  -- Which system generated this draft
  generated_by      TEXT        NOT NULL DEFAULT 'autopilot'
                                CHECK (generated_by IN ('autopilot', 'manual', 'aaron_ai')),

  -- Human-readable explanation of why this draft was triggered
  -- e.g. "Calls below 80% for 4 consecutive weeks"
  trigger_reason    TEXT,

  -- Manager review metadata (populated on approve/reject)
  reviewed_by       UUID        REFERENCES profiles(id) ON DELETE SET NULL,
  reviewed_at       TIMESTAMPTZ,
  review_notes      TEXT,

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ──────────────────────────────────────────────────
-- For manager review queue: pending drafts by org, newest first
CREATE INDEX IF NOT EXISTS idx_idp_drafts_org_status
  ON idp_drafts (organization_id, status, created_at DESC);

-- For pilot adoption signal query:
--   .eq('organization_id', orgId).in('status', ['approved', 'rejected']).gte('updated_at', since)
CREATE INDEX IF NOT EXISTS idx_idp_drafts_org_updated
  ON idp_drafts (organization_id, updated_at DESC)
  WHERE status IN ('approved', 'rejected');

-- For rep-level queries (manager reviewing one rep's drafts)
CREATE INDEX IF NOT EXISTS idx_idp_drafts_profile
  ON idp_drafts (profile_id, status);

-- ── updated_at trigger ────────────────────────────────────────
-- Self-contained trigger function (no moddatetime extension required)
CREATE OR REPLACE FUNCTION set_idp_drafts_updated_at()
  RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER idp_drafts_updated_at
  BEFORE UPDATE ON idp_drafts
  FOR EACH ROW EXECUTE FUNCTION set_idp_drafts_updated_at();

-- ── Row Level Security ────────────────────────────────────────
ALTER TABLE idp_drafts ENABLE ROW LEVEL SECURITY;

-- Managers and admins can read all drafts in their org
CREATE POLICY "idp_drafts_org_read"
  ON idp_drafts FOR SELECT
  USING (organization_id = auth_user_org_id());

-- Only service role (backend / cron) can insert drafts
-- Managers review via API endpoints (which use service role client)
CREATE POLICY "idp_drafts_service_insert"
  ON idp_drafts FOR INSERT
  WITH CHECK (organization_id = auth_user_org_id());

-- Only managers/admins can update (approve/reject) — enforced at API layer too
CREATE POLICY "idp_drafts_org_update"
  ON idp_drafts FOR UPDATE
  USING (organization_id = auth_user_org_id());
